/*******************************************************************************
 * * Copyright 2017 Impetus Infotech.
 * *
 * * Licensed under the Apache License, Version 2.0 (the "License");
 * * you may not use this file except in compliance with the License.
 * * You may obtain a copy of the License at
 * *
 * * http://www.apache.org/licenses/LICENSE-2.0
 * *
 * * Unless required by applicable law or agreed to in writing, software
 * * distributed under the License is distributed on an "AS IS" BASIS,
 * * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * * See the License for the specific language governing permissions and
 * * limitations under the License.
 ******************************************************************************/
package com.impetus.client.kudu.autogeneratedid;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * The Class Employee.
 * 
 * @author devender.yadav
 */
@Entity
@Table(name = "KUDU_EMPLOYEE", schema = "kudutest@kudu-auto-gen-pu")
public class Employee
{

    /** The id. */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String empId;

    /** The name. */
    @Column
    private String name;

    /** The salary. */
    @Column
    private Integer salary;

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public String getId()
    {
        return empId;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(String id)
    {
        this.empId = id;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * Gets the salary.
     * 
     * @return the salary
     */
    public Integer getSalary()
    {
        return salary;
    }

    /**
     * Sets the salary.
     * 
     * @param salary
     *            the new salary
     */
    public void setSalary(int salary)
    {
        this.salary = salary;
    }

}
