package com.impetus.client.crud.autogeneratedid;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "AutoGeneratedUser", schema = "KunderaExamples@mongoTest")
public class AutoGeneratedUser
{

    @GeneratedValue
    @Id
    private String userID;

    @Column(name = "name")
    private String name;

    @OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
    private Set<Document> documents;

    /**
     * @return the userID
     */
    public String getUserID()
    {
        return userID;
    }

    /**
     * @param userID
     *            the userID to set
     */
    public void setUserID(String userID)
    {
        this.userID = userID;
    }

    /**
     * @return the name
     */
    public String getName()
    {
        return name;
    }

    /**
     * @param name
     *            the name to set
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * @return the documents
     */
    public Set<Document> getDocuments()
    {
        return documents;
    }

    /**
     * @param documents
     *            the documents to set
     */
    public void setDocuments(Set<Document> documents)
    {
        this.documents = documents;
    }
}