package com.impetus.client.crud.autogeneratedid;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Document", schema = "KunderaExamples@mongoTest")
public class Document
{

    @GeneratedValue
    @Id
    private String documentID;

    @Column(name = "name")
    private String name;

    @ManyToOne(fetch = FetchType.EAGER)
    private AutoGeneratedUser user;

    public Document()
    {
    }

    public String getDocumentID()
    {
        return documentID;
    }

    public void setDocumentID(String documentID)
    {
        this.documentID = documentID;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public AutoGeneratedUser getUser()
    {
        return user;
    }

    public void setUser(AutoGeneratedUser user)
    {
        this.user = user;
    }
}