package com.impetus.client.crud.autogeneratedid;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "product_ecosystem_map", schema = "KunderaExamples@mongoTest")
public class ProductEcosystemMap implements Serializable
{
    private static final long serialVersionUID = 8153462679027161808L;

    /**
     * Primary key for the table
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column
    private String _id;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "product_id", referencedColumnName = "product_id")
    private Product product;

    @Column(name = "product_ref_id")
    private String productRefId;

    public String get_id()
    {
        return _id;
    }

    public Product getProduct()
    {
        return product;
    }

    public void setProduct(Product product)
    {
        this.product = product;
    }

    public String getProductRefId()
    {
        return productRefId;
    }

    public void setProductRefId(String productRefId)
    {
        this.productRefId = productRefId;
    }
}