package com.impetus.client.crud.autogeneratedid;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Cubicle", schema = "KunderaExamples@mongoTest")
public class Cubicle {
	
	@GeneratedValue
    @Id
    private String cubeID;
	
	
    @Column(name = "name")
    private String name;
    
    @OneToOne(fetch = FetchType.EAGER)
	private EmployeeCubicle residentEmployee;
	
	public String getCubeID()
    {
        return cubeID;
    }

    public void setCubeID(String cubeID)
    {
        this.cubeID = cubeID;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }
    
	//@OneToOne(mappedBy="assignedCubicle")
	public EmployeeCubicle getResidentEmployee() {
	  return residentEmployee;
	}
	
	public void setResidentEmployee(EmployeeCubicle employee) {
	  this.residentEmployee = employee;
	}
}
