package com.impetus.client.crud.autogeneratedid;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import com.impetus.client.utils.MongoUtils;
import com.impetus.kundera.metadata.model.KunderaMetadata;

public class ProductEcosystemMapTest
{
    private static final String _PU = "mongoTest";

    private EntityManagerFactory emf;

    private EntityManager em;

    @Before
    public void setUp() throws Exception
    {
        emf = Persistence.createEntityManagerFactory(_PU);
        em = emf.createEntityManager();
    }

    @After
    public void tearDown() throws Exception
    {
        em.close();
        MongoUtils.dropDatabase(emf, _PU);
        emf.close();
        KunderaMetadata.INSTANCE.setApplicationMetadata(null);
    }

    @Test
    public void test()
    {
        Product product = new Product();
        product.setProductName("Pen");

        em.persist(product);

        em.clear();

        Query q = em.createQuery("Select p from Product p");
        List<Product> products = q.getResultList();

        ProductEcosystemMap ecosystem = new ProductEcosystemMap();
        ecosystem.setProduct(products.get(0));
        ecosystem.setProductRefId("p");

        em.persist(ecosystem);

        em.clear();

        q = em.createQuery("Select p from ProductEcosystemMap p");
        List<ProductEcosystemMap> productMaps = q.getResultList();
        Assert.assertNotNull(productMaps);
        Assert.assertNotNull(productMaps.get(0).getProduct());
    }
}